<?php
/**
 * @file
 * Code for the image card feature.
 */

include_once 'stanford_bean_extras.features.inc';

/**
 * Implements hook_bean_types().
 */
function stanford_bean_extras_bean_types() {
  $plugins = array();
  $plugin_path = drupal_get_path('module', 'stanford_bean_extras') . '/plugins/bean';
  $plugins['stanford_image_card'] = array(
    'handler' => array(
      'class' => 'StanfordImageCard',
      'parent' => 'bean',
    ),
    'path' => $plugin_path,
    'file' => 'StanfordImageCard.class.php',
  );
  return $plugins;
}
