<?php
/**
 * @file
 * Code for the image card feature.
 */

include_once 'stanford_bean_extras.features.inc';

/**
 * Implements hook_bean_types().
 */
function stanford_bean_extras_bean_types() {
  include_once "stanford_bean_extras.bean.inc";
  $plugins = array();
  $plugins = bean_admin_ui_bean_types();
  $extras_plugin_path = drupal_get_path('module', 'stanford_bean_extras') . '/plugins/bean';
  $plugins['stanford_image_card'] = array(
    'name' => 'stanford_image_card',
    'label' => 'stanford_image_card',
    'api_version' => 5,
    'description' => 'Stanford Image Card provides an image, title and url.',
    'handler' => array(
      'class' => 'StanfordImageCard',
      'parent' => 'bean',
      'path' => $extras_plugin_path,
      'file' => 'StanfordImageCard.class.php',
    ),
  );
  return $plugins;
}
